name: Waka Readme
permissions:
  contents: write

on:
  # for manual workflow trigger
  push
#  workflow_dispatch:
 # schedule:
    # runs at 12 AM UTC (5:30 AM IST)
  #  - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: RÃ©mi Boivin
          AUTHOR_EMAIL: remiboivin021[at]gmail.com
          TIME_RANGE: last_6_months
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true